### ISSUE TITLE
Grocery crud's "set relation" method ruins form layout 

### ISSUE THREAD

**Issue by edgar-mtz-e** [Riyadhahmed/Modular-CI-ION-Auth-Grocery-AdminLte#1]
If you add Grocery crud's **"set relation"**  to _Settings_ _Controller_ _like_:

      ```
       $crud->set_relation('name','some_table','some_table_s_field');				
            // render output result
            $output = $crud->render();
            $this->load->view('admin/settings/v_Settings', (array) $output); 
```

the droplist is shown without chosen style and forms is ruined, maybe it has to do with some javascript?

**Comment by Riyadhahmed** [comment]
If you add your own style to drop-down field you may need to create it by call back.
Did you ask me about your drop-down value populate from relation is broken or style not working?
