### ISSUE TITLE
Capital letter in view name for 'all_settings()' in controller 'Settings', creates error in Linux-based hosting

### ISSUE THREAD

**Issue by ghikmawan** [Riyadhahmed/Modular-CI-ION-Auth-Grocery-AdminLte#3]
In the controller Settings.php, function all_settings(), the name of the view to be loaded is 'admin/settings/v_Settings', while the actual file name of the view in folder 'application/modules/admin/views/settings/' is v_settings.php. It causes an error in Linux-based hosting, when clicking the menu Settings in the app.
![issue](https://user-images.githubusercontent.com/14284375/57226896-36202080-703a-11e9-83c2-3aa828a0884b.jpg)

**Comment by Riyadhahmed** [comment]
it worked on localhost without any case-sensitive error but it wont work in live server. i forget to change this spelling. pls change to v_setting  in setting controller
