### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by MayaV369** [Riyadhahmed/Modular-CI-ION-Auth-Grocery-AdminLte#4]
The login page is not working

A PHP Error was encountered
Severity: Notice

Message: Undefined property: stdClass::$file_path

Filename: controllers/Auth.php

Line Number: 58

Backtrace:

File: /opt/bitnami/apache2/htdocs/aya1/application/modules/auth/controllers/Auth.php
Line: 58
Function: _error_handler

File: /opt/bitnami/apache2/htdocs/aya1/application/core/MY_Controller.php
Line: 48
Function: login

File: /opt/bitnami/apache2/htdocs/aya1/index.php
Line: 317
Function: require_once

A Database Error Occurred
Error Number: 1146

Table 'aya1.settings' doesn't exist

SELECT * FROM `settings` WHERE `id` = 1 AND `status` = 1

Filename: modules/admin/models/Settings_model.php

Line Number: 61

**Comment by Riyadhahmed** [comment]
sorry for late reply. please upload db.sql file fro db folder. or create a column file_path in users table hope it works
also i updated the project you can download again
