### ISSUE TITLE
Getting an error (fresh install)

### ISSUE THREAD

**Issue by RCR1984** [Riyadhahmed/Modular-CI-ION-Auth-Grocery-AdminLte#5]
A PHP Error was encountered
Severity: Warning
Message: mkdir(): Invalid path
Filename: drivers/Session_files_driver.php
Line Number: 136
Backtrace:
File: /home/rcr1984/public_html/application/third_party/MX/Loader.php
Line: 175
Function: _ci_load_library 
File: /home/rcr1984/public_html/application/third_party/MX/Loader.php
Line: 191
Function: library 
File: /home/rcr1984/public_html/application/third_party/MX/Loader.php
Line: 155
Function: libraries 
File: /home/rcr1984/public_html/application/third_party/MX/Loader.php
Line: 58
Function: initialize 
File: /home/rcr1984/public_html/application/core/MY_Controller.php
Line: 25
Function: __construct 
File: /home/rcr1984/public_html/application/modules/auth/controllers/Auth.php
Line: 8
Function: __construct 
File: /home/rcr1984/public_html/index.php
Line: 317
Function: require_once 

Fatal error: session_start(): Failed to initialize storage module: user (path: ) in /home/rcr1984/public_html/system/libraries/Session/Session.php on line 143
A PHP Error was encountered
Severity: Error
Message: session_start(): Failed to initialize storage module: user (path: )
Filename: Session/Session.php
Line Number: 143
Backtrace:

**Comment by Riyadhahmed** [comment]
did you import database from db folder?
did you download codeigniter and copy system folder to this project?

**Comment by RCR1984** [comment]
hi, and thnks for the comment.
I did import the database and uploaded a copy of a fresh system folder.
setup my basic settings.
If i run only codeigniter it works fine.

**Comment by Riyadhahmed** [comment]
are you facing any problem now?
