### ISSUE TITLE
Flashing 

### ISSUE THREAD

**Issue by boedyirh** [Riyadhahmed/Modular-CI-ION-Auth-Grocery-AdminLte#6]
Hi, 
This is a very nice starting application. I found that everytime I klik link in menu. The page always flash about one second. It would be nice if it doesnot show like that.

**Comment by Riyadhahmed** [comment]
Hlw, The flash is called page loader. If you don't want to show the page loader then please go to 
application/modules/admin/views/templates/default and edit both file

remove `<div class="se-pre-con"></div>` below body tag

**Comment by boedyirh** [comment]
Thanks
